/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import DB.DB;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.sql.ResultSet;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Chrishmal Rodrigo
 */
public class ItemManagement extends javax.swing.JFrame {

    /**
     * Creates new form ItemManagement
     */
    public ItemManagement() {
        initComponents();
        listfold();
        genarateItemId();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbl_user_icon = new javax.swing.JLabel();
        lbl_user_id = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_suplier = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_catagory = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        btn_remove = new javax.swing.JButton();
        btn_brows = new javax.swing.JButton();
        lbl_image = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_barcode = new javax.swing.JTextField();
        txt_brand = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        yes_Optioon = new javax.swing.JRadioButton();
        no_Option = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        lbl_itmid = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        no_Option1 = new javax.swing.JRadioButton();
        yes_Optioon1 = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jList7 = new javax.swing.JList<>();
        txt_name1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();
        txt_catogory1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList5 = new javax.swing.JList<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jList6 = new javax.swing.JList<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        no_Option2 = new javax.swing.JRadioButton();
        yes_Optioon2 = new javax.swing.JRadioButton();
        yes_Optioon3 = new javax.swing.JRadioButton();
        no_Option3 = new javax.swing.JRadioButton();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        btn_remove1 = new javax.swing.JButton();
        btn_brows1 = new javax.swing.JButton();
        lbl_image1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        txt_search = new javax.swing.JTextField();
        rad_itmName = new javax.swing.JRadioButton();
        rad_itemId = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        update_itm_id = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        txt_suplier2 = new javax.swing.JTextField();
        txt_brand3 = new javax.swing.JTextField();
        txt_barcode2 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        lbl_msg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        jLayeredPane2.setPreferredSize(new java.awt.Dimension(1366, 768));
        jLayeredPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 102, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 102, 204));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel5MouseExited(evt);
            }
        });
        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jPanel5.add(jLabel12);

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 0, 50, 30));

        jLayeredPane2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 30));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        jButton10.setText("jButton10");
        jButton10.setContentAreaFilled(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 110));

        jButton1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/invoice_icon_mini.png"))); // NOI18N
        jButton1.setText("Invoice");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton1.setIconTextGap(30);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 240, 60));

        jButton2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/po_icon_mini.png"))); // NOI18N
        jButton2.setText("P O");
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton2.setIconTextGap(30);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 240, 60));

        jButton7.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new_suplier_icon_mini.png"))); // NOI18N
        jButton7.setText("New Suplier");
        jButton7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton7.setIconTextGap(30);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 240, 60));

        jButton6.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new_item_icon_mini.png"))); // NOI18N
        jButton6.setText("New Item");
        jButton6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton6.setIconTextGap(30);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 240, 60));

        jButton8.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chrishmal Rodrigo\\OneDrive\\Pictures\\hardware\\new_customer_mini.png")); // NOI18N
        jButton8.setText("New Customer");
        jButton8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton8.setIconTextGap(30);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 240, 60));

        jButton9.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chrishmal Rodrigo\\OneDrive\\Pictures\\hardware\\report__icon_mini.png")); // NOI18N
        jButton9.setText("reports");
        jButton9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton9.setIconTextGap(30);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 640, 240, 60));

        jLayeredPane2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 261, 738));

        jPanel7.setBackground(new java.awt.Color(102, 153, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Item Registraton");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 199, 40));

        lbl_user_icon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chrishmal Rodrigo\\OneDrive\\Pictures\\hardware\\admin_icon_mini.png")); // NOI18N
        lbl_user_icon.setText(" ");
        jPanel7.add(lbl_user_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, -1, 40));

        lbl_user_id.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_user_id.setText("user01");
        jPanel7.add(lbl_user_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 0, 70, 40));

        jLayeredPane2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 1106, 40));

        jTabbedPane2.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        jTabbedPane2.setPreferredSize(new java.awt.Dimension(100, 200));

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jList1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jList1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel9.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 250, 90));

        jList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList2MouseClicked(evt);
            }
        });
        jList2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jList2KeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jList2);

        jPanel9.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 250, 90));

        jList3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList3MouseClicked(evt);
            }
        });
        jList3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jList3KeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(jList3);

        jPanel9.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 250, 90));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText(" Item Name");
        jPanel9.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 81, 35));

        txt_name.setPreferredSize(new java.awt.Dimension(35, 0));
        jPanel9.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 250, 35));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Brand");
        jPanel9.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 81, 35));

        txt_suplier.setPreferredSize(new java.awt.Dimension(35, 0));
        txt_suplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_suplierMouseClicked(evt);
            }
        });
        txt_suplier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_suplierKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_suplierKeyReleased(evt);
            }
        });
        jPanel9.add(txt_suplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 250, 35));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Catogory");
        jPanel9.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 81, 35));

        txt_catagory.setPreferredSize(new java.awt.Dimension(35, 0));
        txt_catagory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_catagoryMouseClicked(evt);
            }
        });
        txt_catagory.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_catagoryKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_catagoryKeyReleased(evt);
            }
        });
        jPanel9.add(txt_catagory, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 250, 35));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Suplier");
        jPanel9.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 81, 35));

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Image"));

        btn_remove.setText("Remove");
        btn_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeActionPerformed(evt);
            }
        });

        btn_brows.setText("Browse");
        btn_brows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_browsActionPerformed(evt);
            }
        });

        lbl_image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLayeredPane1.setLayer(btn_remove, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btn_brows, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lbl_image, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(lbl_image, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btn_brows, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_image, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_brows, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );

        jPanel9.add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 320, 290));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Barcode");
        jPanel9.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 510, 87, 35));

        txt_barcode.setPreferredSize(new java.awt.Dimension(35, 0));
        jPanel9.add(txt_barcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, 250, 35));

        txt_brand.setPreferredSize(new java.awt.Dimension(35, 0));
        txt_brand.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_brandMouseClicked(evt);
            }
        });
        txt_brand.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_brandKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_brandKeyReleased(evt);
            }
        });
        jPanel9.add(txt_brand, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 250, 35));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Mesure unite");
        jPanel9.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 81, 35));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "unite", "kg", "g", "ft", "inch", "cube", "l", "ml" }));
        jPanel9.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 250, 35));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Warranty Availability");
        jPanel9.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 510, 140, 35));

        buttonGroup1.add(yes_Optioon);
        yes_Optioon.setText("yes");
        jPanel9.add(yes_Optioon, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 510, -1, 35));

        buttonGroup1.add(no_Option);
        no_Option.setText(" No");
        jPanel9.add(no_Option, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 510, -1, 35));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));

        jLabel14.setText("Item Id :-");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_itmid, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(898, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_itmid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel9.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("expiry date");
        jPanel9.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 440, 140, 35));

        buttonGroup2.add(no_Option1);
        no_Option1.setText(" No");
        jPanel9.add(no_Option1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 440, -1, 35));

        buttonGroup2.add(yes_Optioon1);
        yes_Optioon1.setText("yes");
        jPanel9.add(yes_Optioon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 440, -1, 35));

        jPanel4.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setText("Cancel");
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 210, 50));

        jButton4.setText("Save");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 210, 50));

        jButton5.setText("Clear");
        jPanel4.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 210, 50));

        jPanel9.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 1040, 70));

        jTabbedPane2.addTab("New Item", jPanel9);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jList7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jList7KeyPressed(evt);
            }
        });
        jScrollPane7.setViewportView(jList7);

        jPanel2.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 300, 150));

        txt_name1.setPreferredSize(new java.awt.Dimension(35, 0));
        jPanel2.add(txt_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 250, 35));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText(" Item Name");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 81, 35));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Brand");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 81, 35));

        jList4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList4MouseClicked(evt);
            }
        });
        jList4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jList4KeyPressed(evt);
            }
        });
        jScrollPane4.setViewportView(jList4);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 250, 90));

        txt_catogory1.setPreferredSize(new java.awt.Dimension(35, 0));
        txt_catogory1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_catogory1MouseClicked(evt);
            }
        });
        txt_catogory1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_catogory1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_catogory1KeyReleased(evt);
            }
        });
        jPanel2.add(txt_catogory1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 250, 35));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Catogory");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 81, 35));

        jList5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList5MouseClicked(evt);
            }
        });
        jList5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jList5KeyPressed(evt);
            }
        });
        jScrollPane5.setViewportView(jList5);

        jPanel2.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 250, 90));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Suplier");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 81, 35));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Mesure unite");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 81, 35));

        jList6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList6MouseClicked(evt);
            }
        });
        jList6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jList6KeyPressed(evt);
            }
        });
        jScrollPane6.setViewportView(jList6);

        jPanel2.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 250, 90));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Barcode");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, 87, 35));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Warranty Availability");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 530, 140, 35));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("expiry date");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 460, 140, 35));

        buttonGroup5.add(no_Option2);
        no_Option2.setText(" No");
        jPanel2.add(no_Option2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 460, -1, 35));

        buttonGroup5.add(yes_Optioon2);
        yes_Optioon2.setText("yes");
        jPanel2.add(yes_Optioon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 460, -1, 35));

        buttonGroup4.add(yes_Optioon3);
        yes_Optioon3.setText("yes");
        jPanel2.add(yes_Optioon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 530, -1, 35));

        buttonGroup4.add(no_Option3);
        no_Option3.setText(" No");
        jPanel2.add(no_Option3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 530, -1, 35));

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createTitledBorder("Image"));

        btn_remove1.setText("Remove");
        btn_remove1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_remove1ActionPerformed(evt);
            }
        });

        btn_brows1.setText("Browse");
        btn_brows1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_brows1ActionPerformed(evt);
            }
        });

        lbl_image1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLayeredPane3.setLayer(btn_remove1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(btn_brows1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(lbl_image1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(lbl_image1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btn_brows1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_remove1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_image1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_remove1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_brows1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );

        jPanel2.add(jLayeredPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, 320, 290));

        jPanel8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton11.setText("Cancel");
        jPanel8.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 210, 50));

        jButton12.setText("Update");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 210, 50));

        jButton13.setText("Reset");
        jPanel8.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 210, 50));

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 1040, 70));

        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_searchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });
        jPanel2.add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 300, 30));

        buttonGroup3.add(rad_itmName);
        rad_itmName.setSelected(true);
        rad_itmName.setText("Item Name");
        jPanel2.add(rad_itmName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        buttonGroup3.add(rad_itemId);
        rad_itemId.setText("Item Id");
        jPanel2.add(rad_itemId, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Item id");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 20));

        update_itm_id.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        update_itm_id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(update_itm_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 80, 20));

        jButton14.setText("Search");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, -1, 30));

        txt_suplier2.setPreferredSize(new java.awt.Dimension(35, 0));
        txt_suplier2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_suplier2MouseClicked(evt);
            }
        });
        txt_suplier2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_suplier2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_suplier2KeyReleased(evt);
            }
        });
        jPanel2.add(txt_suplier2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 250, 35));

        txt_brand3.setPreferredSize(new java.awt.Dimension(35, 0));
        txt_brand3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_brand3MouseClicked(evt);
            }
        });
        txt_brand3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_brand3KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_brand3KeyReleased(evt);
            }
        });
        jPanel2.add(txt_brand3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 250, 35));

        txt_barcode2.setPreferredSize(new java.awt.Dimension(35, 0));
        jPanel2.add(txt_barcode2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 530, 250, 35));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "unite", "kg", "g", "ft", "inch", "cube", "l", "ml" }));
        jPanel2.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 250, 35));
        jPanel2.add(lbl_msg, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 290, 30));

        jTabbedPane2.addTab("Update", jPanel2);

        jLayeredPane2.setLayer(jTabbedPane2, javax.swing.JLayeredPane.POPUP_LAYER);
        jLayeredPane2.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 1110, 700));

        getContentPane().add(jLayeredPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseExited
        jPanel5.setBackground(new java.awt.Color(0, 102, 204));
    }//GEN-LAST:event_jPanel5MouseExited

    private void jPanel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseEntered
        jPanel5.setBackground(Color.red);
    }//GEN-LAST:event_jPanel5MouseEntered

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        Home home = new Home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Invoice invoice = new Invoice();
        invoice.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Po po = new Po();
        po.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Suplier suplier = new Suplier();
        suplier.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        ItemManagement item = new ItemManagement();
        item.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Customer customer = new Customer();
        customer.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        Reports report = new Reports();
        report.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void txt_brandKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_brandKeyReleased
        // TODO add your handling code here:
        String brand = txt_brand.getText();
        try {

            ResultSet set1 = DB.search("SELECT name FROM brand WHERE name LIKE '" + brand + "%" + "' ");

            Vector v = new Vector();
            jScrollPane1.setVisible(false);

            while (set1.next()) {

                jScrollPane1.setVisible(true);

                String name = set1.getString("name");

                String showname = name;
                v.add(showname);
                jList1.setListData(v);

            }
            if (txt_brand.getText().equals("")) {
                jScrollPane1.setVisible(false);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txt_brandKeyReleased

    private void txt_brandKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_brandKeyPressed
        if (evt.getKeyCode() == 40) {
            jList1.grabFocus();

            jList1.setSelectedIndex(0);

        }
    }//GEN-LAST:event_txt_brandKeyPressed

    private void txt_brandMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_brandMouseClicked

    }//GEN-LAST:event_txt_brandMouseClicked

    private void btn_browsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_browsActionPerformed
        Image image = selectImage();
        System.out.println(image);
        if (image != null) {
            image = image.getScaledInstance(lbl_image.getWidth(), lbl_image.getHeight(), Image.SCALE_SMOOTH);
            lbl_image.setIcon(new ImageIcon(image));
        }
    }//GEN-LAST:event_btn_browsActionPerformed

    private void btn_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeActionPerformed
        path = null;
        lbl_image.setIcon(null);
    }//GEN-LAST:event_btn_removeActionPerformed

    private void txt_catagoryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_catagoryKeyReleased
        // TODO add your handling code here:
        String catogory = txt_catagory.getText();
        try {

            ResultSet set1 = DB.search("SELECT name FROM catagory WHERE name LIKE '" + catogory + "%" + "' ");

            Vector v = new Vector();
            jScrollPane2.setVisible(false);

            while (set1.next()) {

                jScrollPane2.setVisible(true);

                String name = set1.getString("name");

                String showname = name;
                v.add(showname);
                jList2.setListData(v);

            }
            if (txt_catagory.getText().equals("")) {
                jScrollPane2.setVisible(false);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txt_catagoryKeyReleased

    private void txt_catagoryKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_catagoryKeyPressed
        if (evt.getKeyCode() == 40) {
            jList2.grabFocus();

            jList2.setSelectedIndex(0);

        }
    }//GEN-LAST:event_txt_catagoryKeyPressed

    private void txt_catagoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_catagoryMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_catagoryMouseClicked

    private void txt_suplierKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_suplierKeyReleased
        String supname = txt_suplier.getText();
        try {

            ResultSet set1 = DB.search("SELECT id, fname, company FROM suplier WHERE company LIKE '" + supname + "%" + "' ");

            Vector v = new Vector();
            jScrollPane3.setVisible(false);

            while (set1.next()) {

                jScrollPane3.setVisible(true);
                String id = set1.getString("id");
                String name = set1.getString("fname");
                String company = set1.getString("company");

                String showname = company + " (" + name + ")" + "  -  " + id;
                v.add(showname);
                jList3.setListData(v);

            }
            if (txt_suplier.getText().equals("")) {
                jScrollPane3.setVisible(false);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txt_suplierKeyReleased

    private void txt_suplierKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_suplierKeyPressed
        if (evt.getKeyCode() == 40) {
            jList3.grabFocus();

            jList3.setSelectedIndex(0);

        }
    }//GEN-LAST:event_txt_suplierKeyPressed

    private void txt_suplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_suplierMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_suplierMouseClicked

    private void jList3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList3KeyPressed
        if (evt.getKeyCode() == 10) {
            jScrollPane3.setVisible(false);
            String sname = jList3.getSelectedValue();
            txt_suplier.setText(sname);
            jComboBox1.grabFocus();

        }
    }//GEN-LAST:event_jList3KeyPressed

    private void jList3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList3MouseClicked
        if (jList3.isSelectedIndex(jList3.getSelectedIndex())) {

            txt_suplier.setText(jList3.getSelectedValue());

            jScrollPane3.setVisible(false);
            jComboBox1.grabFocus();
        }
    }//GEN-LAST:event_jList3MouseClicked

    private void jList2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList2KeyPressed
        if (evt.getKeyCode() == 10) {
            jScrollPane2.setVisible(false);
            String sname = jList2.getSelectedValue();
            txt_catagory.setText(sname);
            txt_suplier.grabFocus();

        }
    }//GEN-LAST:event_jList2KeyPressed

    private void jList2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList2MouseClicked
        if (jList2.isSelectedIndex(jList2.getSelectedIndex())) {

            txt_catagory.setText(jList2.getSelectedValue());

            jScrollPane2.setVisible(false);
            txt_suplier.grabFocus();
        }
    }//GEN-LAST:event_jList2MouseClicked

    private void jList1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList1KeyPressed
        if (evt.getKeyCode() == 10) {
            jScrollPane1.setVisible(false);
            String sname = jList1.getSelectedValue();
            txt_brand.setText(sname);
            txt_catagory.grabFocus();

        }
    }//GEN-LAST:event_jList1KeyPressed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        if (jList1.isSelectedIndex(jList1.getSelectedIndex())) {

            txt_brand.setText(jList1.getSelectedValue());

            jScrollPane1.setVisible(false);
            txt_catagory.grabFocus();
        }
    }//GEN-LAST:event_jList1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String id = lbl_itmid.getText();
        String name = txt_name.getText();
        String brand = txt_brand.getText();
        String catagory = txt_catagory.getText();
        String suplier = txt_suplier.getText();
        String munite = jComboBox1.getSelectedItem().toString();
        String barcode = txt_barcode.getText();
        String waranty = no_Option.isSelected() ? "0" : "1";
        String expiry = no_Option1.isSelected() ? "0" : "1";

        try {
            if (brand == "") {
                brand = "No Brand";
            }
            ResultSet set1 = DB.search("SELECT name FROM brand WHERE name = '" + brand + "' ");
            if (!set1.next()) {
                //if you want to add description to brand use here
                DB.iud("INSERT INTO brand VALUES ('" + brand + "')");
            }

            ResultSet set2 = DB.search("SELECT name FROM catagory WHERE name = '" + catagory + "' ");
            if (!set2.next()) {
                //if you want to add description to brand use here
                DB.iud("INSERT INTO catagory VALUES ('" + catagory + "')");
            }

            String supid = suplier.substring(suplier.length() - 8, suplier.length()).replace("-", "").trim();

            System.out.print(supid);
            ResultSet set3 = DB.search("SELECT id FROM suplier WHERE id = '" + supid + "' ");

            if (!set2.next()) {

                DB.iud("INSERT INTO item VALUES ('" + id + "','" + name + "','" + brand + "','" + path + "','" + barcode + "','" + catagory + "','" + supid + "','" + munite + "',1,'" + waranty + "','" + expiry + "')");

                JOptionPane.showMessageDialog(this, "sucsussfull... !");

                txt_name.setText(null);
                txt_brand.setText(null);
                txt_catagory.setText(null);
                txt_suplier.setText(null);
                jComboBox1.setSelectedIndex(0);
                txt_barcode.setText(null);
                no_Option.setSelected(true);
                path = null;
                lbl_image.setIcon(null);
                genarateItemId();

            } else {
                JOptionPane.showMessageDialog(this, " error in Suplier");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_jButton4ActionPerformed

    private void txt_catogory1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_catogory1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_catogory1MouseClicked

    private void txt_catogory1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_catogory1KeyPressed
   if (evt.getKeyCode() == 40) {
            jList5.grabFocus();

            jList5.setSelectedIndex(0);

        }        // TODO add your handling code here:
    }//GEN-LAST:event_txt_catogory1KeyPressed

    private void txt_catogory1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_catogory1KeyReleased
   String catogory = txt_catogory1.getText();
        try {

            ResultSet set1 = DB.search("SELECT name FROM catagory WHERE name LIKE '" + catogory + "%" + "' ");

            Vector v = new Vector();
            jScrollPane5.setVisible(false);

            while (set1.next()) {

                jScrollPane5.setVisible(true);

                String name = set1.getString("name");

                String showname = name;
                v.add(showname);
                jList5.setListData(v);

            }
            if (txt_catogory1.getText().equals("")) {
                jScrollPane5.setVisible(false);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txt_catogory1KeyReleased

    private void jList4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jList4MouseClicked

    private void jList4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList4KeyPressed
   if (evt.getKeyCode() == 10) {
            jScrollPane4.setVisible(false);
            String sname = jList4.getSelectedValue();
            txt_brand3.setText(sname);
            txt_catogory1.grabFocus();

        }      
    }//GEN-LAST:event_jList4KeyPressed

    private void jList5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList5MouseClicked
        if (jList5.isSelectedIndex(jList5.getSelectedIndex())) {

            txt_catogory1.setText(jList5.getSelectedValue());

            jScrollPane5.setVisible(false);
            txt_suplier2.grabFocus();
        }
    }//GEN-LAST:event_jList5MouseClicked

    private void jList5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList5KeyPressed
  if (evt.getKeyCode() == 10) {
            jScrollPane5.setVisible(false);
            String sname = jList5.getSelectedValue();
            txt_catogory1.setText(sname);
            txt_suplier2.grabFocus();

        }        // TODO add your handling code here:
    }//GEN-LAST:event_jList5KeyPressed

    private void jList6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList6MouseClicked
      if (jList6.isSelectedIndex(jList6.getSelectedIndex())) {

            txt_suplier2.setText(jList6.getSelectedValue());

            jScrollPane6.setVisible(false);
            jComboBox2.grabFocus();
        }
    }//GEN-LAST:event_jList6MouseClicked

    private void jList6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList6KeyPressed
if (evt.getKeyCode() == 10) {
            jScrollPane6.setVisible(false);
            String sname = jList6.getSelectedValue();
            txt_suplier2.setText(sname);
            jComboBox2.grabFocus();

        }        // TODO add your handling code here:
    }//GEN-LAST:event_jList6KeyPressed

    private void btn_remove1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_remove1ActionPerformed
        path1 = null;
        lbl_image1.setIcon(null);
    }//GEN-LAST:event_btn_remove1ActionPerformed

    private void btn_brows1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_brows1ActionPerformed
        Image image = selectImage();

        if (image != null) {
            image = image.getScaledInstance(lbl_image1.getWidth(), lbl_image1.getHeight(), Image.SCALE_SMOOTH);
            lbl_image1.setIcon(new ImageIcon(image));
        }
    }//GEN-LAST:event_btn_brows1ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        String id = update_itm_id.getText();
        String name = txt_name1.getText();
        String brand = txt_brand3.getText();
        String catagory = txt_catogory1.getText();
        String suplier = txt_suplier2.getText();
        String munite = jComboBox1.getSelectedItem().toString();
        String barcode = txt_barcode2.getText();
        String waranty = no_Option2.isSelected() ? "0" : "1";
        String expiry = no_Option3.isSelected() ? "0" : "1";

        try {
            if (brand == "") {
                brand = "No Brand";
            }
            ResultSet set1 = DB.search("SELECT name FROM brand WHERE name = '" + brand + "' ");
            if (!set1.next()) {
                //if you want to add description to brand use here
                DB.iud("INSERT INTO brand VALUES ('" + brand + "')");
            }

            ResultSet set2 = DB.search("SELECT name FROM catagory WHERE name = '" + catagory + "' ");
            if (!set2.next()) {
                //if you want to add description to brand use here
                DB.iud("INSERT INTO catagory VALUES ('" + catagory + "')");
            }
            String supid = suplier;
            if (suplier.contains("-")) {
                supid = suplier.substring(suplier.length() - 8, suplier.length()).replace("-", "").trim();
            }

            ResultSet set3 = DB.search("SELECT id FROM suplier WHERE id = '" + supid + "' ");

            if (set3.next()) {

                DB.iud("UPDATE item  SET name ='" + name + "', brand ='" + brand + "', image ='" + path1 + "', barcode ='" + barcode + "', catagory ='" + catagory + "', suplier ='" + supid + "', mesure_unite ='" + munite + "', waranty ='" + waranty + "', isexpire ='" + expiry + "' WHERE  id = '" + id + "'");

                JOptionPane.showMessageDialog(this, "Update sucsussfull... !");

                txt_name.setText(null);
                txt_brand.setText(null);
                txt_catagory.setText(null);
                txt_suplier.setText(null);
                jComboBox1.setSelectedIndex(0);
                txt_barcode.setText(null);
                no_Option.setSelected(true);
                path = null;
                lbl_image.setIcon(null);
                genarateItemId();

            } else {
                JOptionPane.showMessageDialog(this, " error in Suplier");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton12ActionPerformed

    private void txt_searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyPressed
        if (jList7.isVisible()) {

            if (evt.getKeyCode() == 40) {
                jList7.grabFocus();
                jList7.setSelectedIndex(0);
            }
        }


    }//GEN-LAST:event_txt_searchKeyPressed

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        if (!lbl_msg.getText().equals("")) {
            lbl_msg.setText("");
        }
        if (rad_itmName.isSelected()) {
            try {
                String text = txt_search.getText();
                ResultSet set2 = DB.search("SELECT id, name FROM item WHERE name LIKE '" + "%" + text + "%" + "' ");
                Vector v = new Vector();
                jScrollPane7.setVisible(false);

                while (set2.next()) {

                    jScrollPane7.setVisible(true);
                    String id = set2.getString("id");
                    String name = set2.getString("name");

                    String showname = name + "  -  " + id;
                    v.add(showname);
                    jList7.setListData(v);

                }
                if (txt_search.getText().isEmpty()) {
                    jScrollPane7.setVisible(false);
                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            jScrollPane7.setVisible(false);
        }

    }//GEN-LAST:event_txt_searchKeyReleased

    private void jList7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList7KeyPressed

        if (evt.getKeyCode() == 10) {

            path1 = null;
            txt_name1.setText(null);
            txt_brand3.setText(null);
            txt_catogory1.setText(null);
            txt_suplier2.setText(null);
            jComboBox2.setSelectedIndex(0);
            txt_barcode2.setText(null);
            no_Option2.setSelected(true);
            no_Option3.setSelected(true);

            lbl_image1.setIcon(null);

            if (!jList7.isSelectionEmpty()) {
                String value = jList7.getSelectedValue();
                String[] itmName = jList7.getSelectedValue().split("  -  ");

                txt_search.setText(value);
                String item = itmName[1];
                jScrollPane7.setVisible(false);
                update_itm_id.setText(item);

                try {
                    ResultSet search = DB.search("SELECT name,brand,image,barcode,suplier,mesure_unite,waranty,isexpire FROM item WHERE id = '" + item + "'");
                    if (search.next()) {
                        txt_name1.setText(search.getString("name"));
                        txt_catogory1.setText(search.getString("brand"));
                        path1 = search.getString("image");

                        if (!path1.equals("null")) {
                            File file = new File(path1);
                            Image image = ImageIO.read(file);

                            image = image.getScaledInstance(lbl_image1.getWidth(), lbl_image1.getHeight(), Image.SCALE_SMOOTH);
                            lbl_image1.setIcon(new ImageIcon(image));

                        }
                        txt_barcode2.setText(search.getString("barcode"));
                        txt_suplier2.setText(search.getString("suplier"));
                        String m_unite = search.getString("mesure_unite");
                        jComboBox2.setSelectedItem(m_unite);
                        if (search.getBoolean("waranty")) {
                            yes_Optioon3.setSelected(true);
                        } else {
                            no_Option3.setSelected(true);
                        }
                        if (search.getBoolean("isexpire")) {
                            yes_Optioon2.setSelected(true);
                        } else {
                            no_Option2.setSelected(true);
                        }

                    }

                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_jList7KeyPressed

    private void txt_suplier2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_suplier2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_suplier2MouseClicked

    private void txt_suplier2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_suplier2KeyPressed
      if (evt.getKeyCode() == 40) {
            jList6.grabFocus();

            jList6.setSelectedIndex(0);

        }        // TODO add your handling code here:
    }//GEN-LAST:event_txt_suplier2KeyPressed

    private void txt_suplier2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_suplier2KeyReleased
          String supname = txt_suplier2.getText();
        try {

            ResultSet set1 = DB.search("SELECT id, fname, company FROM suplier WHERE company LIKE '" + supname + "%" + "' ");

            Vector v = new Vector();
            jScrollPane6.setVisible(false);

            while (set1.next()) {

                jScrollPane6.setVisible(true);
                String id = set1.getString("id");
                String name = set1.getString("fname");
                String company = set1.getString("company");

                String showname = company + " (" + name + ")" + "  -  " + id;
                v.add(showname);
                jList6.setListData(v);

            }
            if (txt_suplier2.getText().equals("")) {
                jScrollPane6.setVisible(false);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txt_suplier2KeyReleased

    private void txt_brand3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_brand3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_brand3MouseClicked

    private void txt_brand3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_brand3KeyPressed
          if (evt.getKeyCode() == 40) {
            jList4.grabFocus();

            jList4.setSelectedIndex(0);

        }
    }//GEN-LAST:event_txt_brand3KeyPressed

    private void txt_brand3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_brand3KeyReleased
     String brand = txt_brand3.getText();
        try {

            ResultSet set1 = DB.search("SELECT name FROM brand WHERE name LIKE '" + brand + "%" + "' ");

            Vector v = new Vector();
            jScrollPane4.setVisible(false);

            while (set1.next()) {

                jScrollPane4.setVisible(true);

                String name = set1.getString("name");

                String showname = name;
                v.add(showname);
                jList4.setListData(v);

            }
            if (txt_brand3.getText().equals("")) {
                jScrollPane4.setVisible(false);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txt_brand3KeyReleased

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        if (rad_itemId.isSelected()) {

            String item = txt_search.getText();

                   path1 = null;
            txt_name1.setText(null);
            txt_brand3.setText(null);
            txt_catogory1.setText(null);
            txt_suplier2.setText(null);
            jComboBox2.setSelectedIndex(0);
            txt_barcode2.setText(null);
            no_Option2.setSelected(true);
            no_Option3.setSelected(true);

            lbl_image1.setIcon(null);
            
            try {
                ResultSet search = DB.search("SELECT name,brand,image,barcode,suplier,mesure_unite,waranty,isexpire FROM item WHERE id = '" + item + "'");
                if (search.next()) {
                    txt_name1.setText(search.getString("name"));
                    txt_catogory1.setText(search.getString("brand"));
                    path1 = search.getString("image");
                    System.out.println(path1);
                    if (!path1.equals("null")) {
                        File file = new File(path1);
                        Image image = ImageIO.read(file);

                        image = image.getScaledInstance(lbl_image1.getWidth(), lbl_image1.getHeight(), Image.SCALE_SMOOTH);
                        lbl_image1.setIcon(new ImageIcon(image));

                    }
                    txt_barcode2.setText(search.getString("barcode"));
                    txt_suplier2.setText(search.getString("suplier"));
                    String m_unite = search.getString("mesure_unite");
                    jComboBox2.setSelectedItem(m_unite);
                    if (search.getBoolean("waranty")) {
                        yes_Optioon3.setSelected(true);
                    } else {
                        no_Option3.setSelected(true);
                    }
                    if (search.getBoolean("isexpire")) {
                        yes_Optioon2.setSelected(true);
                    } else {
                        no_Option2.setSelected(true);
                    }

                } else {
                    lbl_msg.setText("Invalid input");
                }

            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_jButton14ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItemManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItemManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItemManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItemManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ItemManagement().setVisible(true);
            }
        });
    }

    private void listfold() {
        jScrollPane1.setVisible(false);
        jScrollPane2.setVisible(false);
        jScrollPane3.setVisible(false);
        jScrollPane4.setVisible(false);
        jScrollPane5.setVisible(false);
        jScrollPane6.setVisible(false);
        jScrollPane7.setVisible(false);
    }

    private void genarateItemId() {
        try {
            ResultSet dataFetch = DB.search("select count('item') as x from item");
            if (dataFetch.next()) {
                int count = Integer.parseInt(dataFetch.getString("x"));
                count++;
                lbl_itmid.setText("ITM" + count);
                txt_name.grabFocus();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    Image selectImage() {
        JFileChooser chooser = new JFileChooser();
        Image image = null;
        int i = chooser.showOpenDialog(this);
        if (i == JFileChooser.APPROVE_OPTION) {
            try {
                File file = chooser.getSelectedFile();
                path = file.getAbsolutePath().replace("\\", "/");
                image = ImageIO.read(file);
                return image;

            } catch (Exception e) {
                e.printStackTrace();
            }

        }

        return image;
    }

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_brows;
    private javax.swing.JButton btn_brows1;
    private javax.swing.JButton btn_remove;
    private javax.swing.JButton btn_remove1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JList<String> jList4;
    private javax.swing.JList<String> jList5;
    private javax.swing.JList<String> jList6;
    private javax.swing.JList<String> jList7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lbl_image;
    private javax.swing.JLabel lbl_image1;
    private javax.swing.JLabel lbl_itmid;
    private javax.swing.JLabel lbl_msg;
    private javax.swing.JLabel lbl_user_icon;
    private javax.swing.JLabel lbl_user_id;
    private javax.swing.JRadioButton no_Option;
    private javax.swing.JRadioButton no_Option1;
    private javax.swing.JRadioButton no_Option2;
    private javax.swing.JRadioButton no_Option3;
    private javax.swing.JRadioButton rad_itemId;
    private javax.swing.JRadioButton rad_itmName;
    private javax.swing.JTextField txt_barcode;
    private javax.swing.JTextField txt_barcode2;
    private javax.swing.JTextField txt_brand;
    private javax.swing.JTextField txt_brand3;
    private javax.swing.JTextField txt_catagory;
    private javax.swing.JTextField txt_catogory1;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_name1;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_suplier;
    private javax.swing.JTextField txt_suplier2;
    private javax.swing.JLabel update_itm_id;
    private javax.swing.JRadioButton yes_Optioon;
    private javax.swing.JRadioButton yes_Optioon1;
    private javax.swing.JRadioButton yes_Optioon2;
    private javax.swing.JRadioButton yes_Optioon3;
    // End of variables declaration//GEN-END:variables

    String path;
    String path1;

}
