/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import DB.DB;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.sql.ResultSet;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mondrian.util.Base64;
import org.apache.tools.ant.taskdefs.Sleep;

/**
 *
 * @author Chrishmal Rodrigo
 */
public class ItemRegistration extends javax.swing.JFrame {

    /**
     * Creates new form ItemManagement
     */
    public ItemRegistration() {
        initComponents();
        listfold();
        genarateItemId();

    }

    ItemRegistration(String id) {
        initComponents();
        listfold();
        loadDetails(id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jPanel4 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_suplier = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_catagory = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        btn_remove = new javax.swing.JButton();
        btn_brows = new javax.swing.JButton();
        lbl_image = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_barcode = new javax.swing.JTextField();
        txt_brand = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        yes_Optioon = new javax.swing.JRadioButton();
        no_Option = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        lbl_itmid = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        no_Option1 = new javax.swing.JRadioButton();
        yes_Optioon1 = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        txt_lowqty = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        jLayeredPane2.setPreferredSize(new java.awt.Dimension(1366, 768));
        jLayeredPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(java.awt.Color.white);
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setFont(new java.awt.Font("Nunito", 0, 18)); // NOI18N
        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 20, 210, 50));

        jButton4.setFont(new java.awt.Font("Nunito", 0, 18)); // NOI18N
        jButton4.setText("Save");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 210, 50));

        jButton5.setFont(new java.awt.Font("Nunito", 0, 18)); // NOI18N
        jButton5.setText("Clear");
        jPanel4.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 210, 50));

        jLayeredPane2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 689, 1106, 79));

        jPanel9.setBackground(java.awt.Color.white);
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N

        jList1.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jList1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jList1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel9.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 250, 90));

        jScrollPane2.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N

        jList2.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        jList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList2MouseClicked(evt);
            }
        });
        jList2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jList2KeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jList2);

        jPanel9.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 250, 90));

        jScrollPane3.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N

        jList3.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        jList3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList3MouseClicked(evt);
            }
        });
        jList3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jList3KeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(jList3);

        jPanel9.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, 250, 90));

        jLabel1.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        jLabel1.setText(" Item Name");
        jPanel9.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 100, 35));

        txt_name.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        txt_name.setPreferredSize(new java.awt.Dimension(35, 0));
        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });
        jPanel9.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 250, 35));

        jLabel4.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        jLabel4.setText("Brand");
        jPanel9.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 100, 35));

        txt_suplier.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        txt_suplier.setPreferredSize(new java.awt.Dimension(35, 0));
        txt_suplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_suplierMouseClicked(evt);
            }
        });
        txt_suplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_suplierActionPerformed(evt);
            }
        });
        txt_suplier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_suplierKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_suplierKeyReleased(evt);
            }
        });
        jPanel9.add(txt_suplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 250, 35));

        jLabel5.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        jLabel5.setText("Catogory");
        jPanel9.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 100, 35));

        txt_catagory.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        txt_catagory.setPreferredSize(new java.awt.Dimension(35, 0));
        txt_catagory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_catagoryMouseClicked(evt);
            }
        });
        txt_catagory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_catagoryActionPerformed(evt);
            }
        });
        txt_catagory.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_catagoryKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_catagoryKeyReleased(evt);
            }
        });
        jPanel9.add(txt_catagory, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 250, 35));

        jLabel7.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        jLabel7.setText("Suplier");
        jPanel9.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 100, 35));

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Image", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Nunito SemiBold", 1, 14))); // NOI18N
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_remove.setBackground(java.awt.Color.white);
        btn_remove.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        btn_remove.setText("Remove");
        btn_remove.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        btn_remove.setContentAreaFilled(false);
        btn_remove.setFocusPainted(false);
        btn_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeActionPerformed(evt);
            }
        });
        jLayeredPane1.add(btn_remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 269, 75, 30));

        btn_brows.setBackground(java.awt.Color.white);
        btn_brows.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        btn_brows.setText("Browse");
        btn_brows.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        btn_brows.setContentAreaFilled(false);
        btn_brows.setFocusPainted(false);
        btn_brows.setFocusTraversalPolicyProvider(true);
        btn_brows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_browsActionPerformed(evt);
            }
        });
        jLayeredPane1.add(btn_brows, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 269, 75, 30));

        lbl_image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLayeredPane1.add(lbl_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 31, 171, 181));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/remove-file.png"))); // NOI18N
        jLayeredPane1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 235, 75, 33));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search (1).png"))); // NOI18N
        jLayeredPane1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 235, 75, 33));

        jPanel9.add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, 320, 300));

        jLabel11.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        jLabel11.setText("Barcode");
        jPanel9.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, 110, 35));

        txt_barcode.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        txt_barcode.setPreferredSize(new java.awt.Dimension(35, 0));
        jPanel9.add(txt_barcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, 250, 35));

        txt_brand.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        txt_brand.setPreferredSize(new java.awt.Dimension(35, 0));
        txt_brand.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_brandMouseClicked(evt);
            }
        });
        txt_brand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_brandActionPerformed(evt);
            }
        });
        txt_brand.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_brandKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_brandKeyReleased(evt);
            }
        });
        jPanel9.add(txt_brand, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 250, 35));

        jLabel13.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        jLabel13.setText("Mesure Unite");
        jPanel9.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 100, 35));

        jComboBox1.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "unit", "kg", "g", "ft", "inch", "cube", "l", "ml" }));
        jComboBox1.setOpaque(false);
        jPanel9.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 250, 35));

        jLabel15.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        jLabel15.setText("Low Quantity");
        jPanel9.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 520, 160, 35));

        buttonGroup1.add(yes_Optioon);
        yes_Optioon.setFont(new java.awt.Font("Nunito", 0, 14)); // NOI18N
        yes_Optioon.setText("yes");
        yes_Optioon.setContentAreaFilled(false);
        jPanel9.add(yes_Optioon, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 470, -1, 35));

        buttonGroup1.add(no_Option);
        no_Option.setFont(new java.awt.Font("Nunito", 0, 14)); // NOI18N
        no_Option.setSelected(true);
        no_Option.setText(" No");
        no_Option.setContentAreaFilled(false);
        jPanel9.add(no_Option, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 470, -1, 35));

        jPanel6.setBackground(java.awt.Color.white);
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));

        jLabel14.setFont(new java.awt.Font("Nunito", 0, 14)); // NOI18N
        jLabel14.setText("Item ID :-");

        lbl_itmid.setFont(new java.awt.Font("Nunito", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_itmid, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(954, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_itmid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel9.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1106, 30));

        jLabel16.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        jLabel16.setText("Expiry Date");
        jPanel9.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 430, 160, 35));

        buttonGroup2.add(no_Option1);
        no_Option1.setFont(new java.awt.Font("Nunito", 0, 14)); // NOI18N
        no_Option1.setSelected(true);
        no_Option1.setText(" No");
        no_Option1.setContentAreaFilled(false);
        jPanel9.add(no_Option1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 430, -1, 35));

        buttonGroup2.add(yes_Optioon1);
        yes_Optioon1.setFont(new java.awt.Font("Nunito", 0, 14)); // NOI18N
        yes_Optioon1.setText("yes");
        yes_Optioon1.setContentAreaFilled(false);
        jPanel9.add(yes_Optioon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 430, -1, 35));

        jLabel22.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        jLabel22.setText("Warranty Availability");
        jPanel9.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 470, 160, 35));

        txt_lowqty.setFont(new java.awt.Font("Nunito", 0, 14)); // NOI18N
        txt_lowqty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_lowqtyActionPerformed(evt);
            }
        });
        jPanel9.add(txt_lowqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 520, 110, 25));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/middle line.png"))); // NOI18N
        jLabel8.setOpaque(true);
        jPanel9.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, 10, 430));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/middle line.png"))); // NOI18N
        jLabel17.setOpaque(true);
        jPanel9.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 10, 430));

        jLayeredPane2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 69, 1104, 620));

        jPanel10.setBackground(new java.awt.Color(16, 52, 166));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new Color(0.0f, 0.0f, 0.0f, 0.0f));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel5MouseExited(evt);
            }
        });
        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jLabel12.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(255, 0, 0)));
        jPanel5.add(jLabel12);

        jPanel10.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 0, 60, 30));

        jLabel9.setFont(new java.awt.Font("Nunito", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/paint-brush.png"))); // NOI18N
        jLabel9.setText("MELO HARDWARE & PAINT HOUSE");
        jPanel10.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 3, 330, 25));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/heder_image-1.png"))); // NOI18N
        jPanel10.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 30));

        jLayeredPane2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, -1));

        jPanel7.setBackground(new java.awt.Color(106, 162, 186));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Nunito ExtraBold", 1, 24)); // NOI18N
        jLabel3.setText("Item Registration");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 330, 29));

        jLayeredPane2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 1106, 40));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 110));

        jButton1.setFont(new java.awt.Font("Nunito Black", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/invoice_icon_mini.png"))); // NOI18N
        jButton1.setText("Invoice");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton1.setIconTextGap(30);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 240, 60));

        jButton2.setFont(new java.awt.Font("Nunito Black", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/po_icon_mini.png"))); // NOI18N
        jButton2.setText("P O");
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton2.setIconTextGap(30);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 240, 60));

        jButton7.setFont(new java.awt.Font("Nunito Black", 1, 14)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new_suplier_icon_mini.png"))); // NOI18N
        jButton7.setText("New Suplier");
        jButton7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton7.setIconTextGap(30);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 240, 60));

        jButton6.setFont(new java.awt.Font("Nunito Black", 1, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new_item_icon_mini.png"))); // NOI18N
        jButton6.setText("New Item");
        jButton6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton6.setIconTextGap(30);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 240, 60));

        jButton12.setFont(new java.awt.Font("Nunito Black", 1, 14)); // NOI18N
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new_customer_mini.png"))); // NOI18N
        jButton12.setText("New Customer");
        jButton12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton12.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton12.setIconTextGap(30);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 240, 60));

        jButton13.setFont(new java.awt.Font("Nunito Black", 1, 14)); // NOI18N
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new_employee_icon-mini.png"))); // NOI18N
        jButton13.setText("New Employee");
        jButton13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton13.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton13.setIconTextGap(30);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 640, 240, 60));

        jLayeredPane2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 261, 738));

        getContentPane().add(jLayeredPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_brandKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_brandKeyReleased
        // TODO add your handling code here:
        String brand = txt_brand.getText();
        try {

            ResultSet set1 = DB.search("SELECT name FROM brand WHERE name LIKE '" + brand + "%" + "' ");

            Vector v = new Vector();
            jScrollPane1.setVisible(false);

            while (set1.next()) {

                jScrollPane1.setVisible(true);

                String name = set1.getString("name");

                String showname = name;
                v.add(showname);
                jList1.setListData(v);

            }
            if (txt_brand.getText().equals("")) {
                jScrollPane1.setVisible(false);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txt_brandKeyReleased

    private void txt_brandKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_brandKeyPressed
        if (evt.getKeyCode() == 40) {
            jList1.grabFocus();

            jList1.setSelectedIndex(0);

        }
    }//GEN-LAST:event_txt_brandKeyPressed

    private void txt_brandMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_brandMouseClicked

    }//GEN-LAST:event_txt_brandMouseClicked

    private void btn_browsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_browsActionPerformed
        Image image = selectImage();

        if (image != null) {
            image = image.getScaledInstance(lbl_image.getWidth(), lbl_image.getHeight(), Image.SCALE_SMOOTH);
            lbl_image.setIcon(new ImageIcon(image));
        }
    }//GEN-LAST:event_btn_browsActionPerformed

    private void btn_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeActionPerformed
        path = null;
        lbl_image.setIcon(null);
    }//GEN-LAST:event_btn_removeActionPerformed

    private void txt_catagoryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_catagoryKeyReleased
        // TODO add your handling code here:
        String catogory = txt_catagory.getText();
        try {

            ResultSet set1 = DB.search("SELECT name FROM catagory WHERE name LIKE '" + catogory + "%" + "' ");

            Vector v = new Vector();
            jScrollPane2.setVisible(false);

            while (set1.next()) {

                jScrollPane2.setVisible(true);

                String name = set1.getString("name");

                String showname = name;
                v.add(showname);
                jList2.setListData(v);

            }
            if (txt_catagory.getText().equals("")) {
                jScrollPane2.setVisible(false);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txt_catagoryKeyReleased

    private void txt_catagoryKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_catagoryKeyPressed
        if (evt.getKeyCode() == 40) {
            jList2.grabFocus();

            jList2.setSelectedIndex(0);

        }
    }//GEN-LAST:event_txt_catagoryKeyPressed

    private void txt_catagoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_catagoryMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_catagoryMouseClicked

    private void txt_suplierKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_suplierKeyReleased
        String supname = txt_suplier.getText();
        try {

            ResultSet set1 = DB.search("SELECT id, fname, company FROM suplier WHERE company LIKE '" + supname + "%" + "' ");

            Vector v = new Vector();
            jScrollPane3.setVisible(false);

            while (set1.next()) {

                jScrollPane3.setVisible(true);
                String id = set1.getString("id");
                String name = set1.getString("fname");
                String company = set1.getString("company");

                String showname = company + " (" + name + ")" + "  -  " + id;
                v.add(showname);
                jList3.setListData(v);

            }
            if (txt_suplier.getText().equals("")) {
                jScrollPane3.setVisible(false);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txt_suplierKeyReleased

    private void txt_suplierKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_suplierKeyPressed
        if (evt.getKeyCode() == 40) {
            jList3.grabFocus();

            jList3.setSelectedIndex(0);

        }
    }//GEN-LAST:event_txt_suplierKeyPressed

    private void txt_suplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_suplierMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_suplierMouseClicked

    private void jList3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList3KeyPressed
        if (evt.getKeyCode() == 10) {
            jScrollPane3.setVisible(false);
            String sname = jList3.getSelectedValue();
            txt_suplier.setText(sname);
            jComboBox1.grabFocus();

        }
    }//GEN-LAST:event_jList3KeyPressed

    private void jList3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList3MouseClicked
        if (jList3.isSelectedIndex(jList3.getSelectedIndex())) {

            txt_suplier.setText(jList3.getSelectedValue());

            jScrollPane3.setVisible(false);
            jComboBox1.grabFocus();
        }
    }//GEN-LAST:event_jList3MouseClicked

    private void jList2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList2KeyPressed
        if (evt.getKeyCode() == 10) {
            jScrollPane2.setVisible(false);
            String sname = jList2.getSelectedValue();
            txt_catagory.setText(sname);
            txt_suplier.grabFocus();

        }
    }//GEN-LAST:event_jList2KeyPressed

    private void jList2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList2MouseClicked
        if (jList2.isSelectedIndex(jList2.getSelectedIndex())) {

            txt_catagory.setText(jList2.getSelectedValue());

            jScrollPane2.setVisible(false);
            txt_suplier.grabFocus();
        }
    }//GEN-LAST:event_jList2MouseClicked

    private void jList1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList1KeyPressed
        if (evt.getKeyCode() == 10) {
            jScrollPane1.setVisible(false);
            String sname = jList1.getSelectedValue();
            txt_brand.setText(sname);
            txt_catagory.grabFocus();

        }
    }//GEN-LAST:event_jList1KeyPressed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        if (jList1.isSelectedIndex(jList1.getSelectedIndex())) {

            txt_brand.setText(jList1.getSelectedValue());

            jScrollPane1.setVisible(false);
            txt_catagory.grabFocus();
        }
    }//GEN-LAST:event_jList1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String id = lbl_itmid.getText();
        String name = txt_name.getText();
        String brand = txt_brand.getText();
        String catagory = txt_catagory.getText();
        String suplier = txt_suplier.getText();
        String munite = jComboBox1.getSelectedItem().toString();
        String barcode = txt_barcode.getText();
        String waranty = no_Option.isSelected() ? "0" : "1";
        String expiry = no_Option1.isSelected() ? "0" : "1";
        int low_qty = Integer.parseInt(txt_lowqty.getText());

        try {
            if (brand.equals("")) {
                brand = "No Brand";
            }
            ResultSet set1 = DB.search("SELECT name FROM brand WHERE name = '" + brand + "' ");
            if (!set1.next()) {
                //if you want to add description to brand use here
                DB.iud("INSERT INTO brand VALUES ('" + brand + "')");
            }

            ResultSet set2 = DB.search("SELECT name FROM catagory WHERE name = '" + catagory + "' ");
            if (!set2.next()) {
                //if you want to add description to brand use here
                DB.iud("INSERT INTO catagory VALUES ('" + catagory + "')");
            }

            String supid = suplier.substring(suplier.length() - 8, suplier.length()).replace("-", "").trim();

            ResultSet set3 = DB.search("SELECT id FROM suplier WHERE id = '" + supid + "' ");
            if (!set3.next()) {
                Suplier sup = new Suplier();
                Thread t = new Thread() {
                    @Override
                    public void run() {

                        sup.setVisible(true);

                        txt_suplier.setText(null);

                    }

                };
                JOptionPane.showMessageDialog(this, "save new suplier");
                t.start();
                sup.toFront();
                sup.requestFocus();

            } else {
                if (jButton4.getText().equals("Save")) {
                    DB.iud("INSERT INTO item VALUES ('" + id + "','" + name + "','" + brand + "','" + path + "','" + barcode + "','" + catagory + "','" + supid + "','" + munite + "',1,'" + waranty + "','" + expiry + "','" + low_qty + "')");
                    DB.iud("INSERT INTO quntity VALUES ('" + id + "','" + 0.0 + "')");
                    JOptionPane.showMessageDialog(this, "Sucsussfully Saved... !");

                    txt_name.setText(null);
                    txt_brand.setText(null);
                    txt_catagory.setText(null);
                    txt_suplier.setText(null);
                    txt_lowqty.setText(null);
                    jComboBox1.setSelectedIndex(0);
                    txt_barcode.setText(null);
                    no_Option.setSelected(true);
                    path = null;
                    lbl_image.setIcon(null);
                    genarateItemId();
                } else {

                     DB.iud("UPDATE item SET name = '" + name + "', brand ='" + brand + "', image = '" + path + "',barcode = '" + barcode + "',catagory = '" + catagory + "',suplier = '" + supid + "', mesure_unite = '" + munite + "',waranty = '" + waranty + "',isexpire = '" + expiry + "',lowqty = '" + low_qty + "' WHERE id = '"+id+"'");
                   
                    JOptionPane.showMessageDialog(this, "Sucsussfully Updated... !");

                    txt_name.setText(null);
                    txt_brand.setText(null);
                    txt_catagory.setText(null);
                    txt_suplier.setText(null);
                    txt_lowqty.setText(null);
                    jComboBox1.setSelectedIndex(0);
                    txt_barcode.setText(null);
                    no_Option.setSelected(true);
                    path = null;
                    lbl_image.setIcon(null);
                    jButton4.setText("Save");
                    genarateItemId();
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_jButton4ActionPerformed

    private void txt_lowqtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_lowqtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lowqtyActionPerformed

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        txt_brand.grabFocus();
    }//GEN-LAST:event_txt_nameActionPerformed

    private void txt_brandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_brandActionPerformed
        txt_catagory.grabFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txt_brandActionPerformed

    private void txt_catagoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_catagoryActionPerformed
        // TODO add your handling code here:
        txt_suplier.grabFocus();
    }//GEN-LAST:event_txt_catagoryActionPerformed

    private void txt_suplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_suplierActionPerformed
        jComboBox1.grabFocus();
    }//GEN-LAST:event_txt_suplierActionPerformed

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jPanel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseEntered
        jPanel5.setBackground(new Color(0.0f, 0.0f, 0.0f, 0.0f));
    }//GEN-LAST:event_jPanel5MouseEntered

    private void jPanel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseExited

    }//GEN-LAST:event_jPanel5MouseExited

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

        Home home = new Home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Invoice invoice = new Invoice();
        invoice.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Po po = new Po();
        po.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Suplier suplier = new Suplier();
        suplier.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        ItemRegistration item = new ItemRegistration();
        item.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        Customer customer = new Customer();
        customer.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed

        Employee employee = new Employee();
        employee.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ItemSearch item = new ItemSearch();
        item.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItemRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItemRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItemRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItemRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ItemRegistration().setVisible(true);
            }
        });
    }

    private void listfold() {
        jScrollPane1.setVisible(false);
        jScrollPane2.setVisible(false);
        jScrollPane3.setVisible(false);

    }

    private void genarateItemId() {
        try {
            ResultSet dataFetch = DB.search("select count('item') as x from item");
            if (dataFetch.next()) {
                int count = Integer.parseInt(dataFetch.getString("x"));
                count++;
                lbl_itmid.setText("ITM" + count);
                txt_name.grabFocus();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    Image selectImage() {
        JFileChooser chooser = new JFileChooser();
        Image image = null;
        int i = chooser.showOpenDialog(this);
        if (i == JFileChooser.APPROVE_OPTION) {
            try {
                File file = chooser.getSelectedFile();
                path = file.getAbsolutePath().replace("\\", "/");
                image = ImageIO.read(file);
                return image;

            } catch (Exception e) {
                e.printStackTrace();
            }

        }

        return image;
    }

    void loadDetails(String id) {
        try {
            ResultSet search = DB.search("SELECT * FROM item WHERE id = '" + id + "'");
            if (search.next()) {
                lbl_itmid.setText(id);
                txt_name.setText(search.getString("name"));
                txt_catagory.setText(search.getString("catagory"));
                txt_brand.setText(search.getString("brand"));
                jComboBox1.setSelectedItem(search.getString("mesure_unite"));
                txt_barcode.setText(search.getString("barcode"));
                if (search.getBoolean("waranty")) {
                    yes_Optioon.setSelected(true);
                } else {
                    no_Option.setSelected(true);
                }
                if (search.getBoolean("isexpire")) {
                    yes_Optioon1.setSelected(true);
                } else {
                    no_Option1.setSelected(true);
                }

                txt_lowqty.setText(search.getString("lowqty"));

                String suplier = search.getString("suplier");
                ResultSet set1 = DB.search("SELECT fname, company FROM suplier WHERE id = '" + suplier + "' ");
                if (set1.next()) {

                    String name = set1.getString("fname");
                    String company = set1.getString("company");

                    String showname = company + " (" + name + ")" + "  -  " + suplier;
                    txt_suplier.setText(showname);
                }

                String img = search.getString("image");
                path = img;
                if (!(path.isEmpty() || path.equals("null"))) {
                    System.out.println(path);
                    File file = new File(path);
                    Image image = ImageIO.read(file);
                    if (image != null) {
                        image = image.getScaledInstance(lbl_image.getWidth(), lbl_image.getHeight(), Image.SCALE_SMOOTH);
                        lbl_image.setIcon(new ImageIcon(image));
                    }
                }
                jButton4.setText("Update");

            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_brows;
    private javax.swing.JButton btn_remove;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_image;
    private javax.swing.JLabel lbl_itmid;
    private javax.swing.JRadioButton no_Option;
    private javax.swing.JRadioButton no_Option1;
    private javax.swing.JTextField txt_barcode;
    private javax.swing.JTextField txt_brand;
    private javax.swing.JTextField txt_catagory;
    private javax.swing.JTextField txt_lowqty;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_suplier;
    private javax.swing.JRadioButton yes_Optioon;
    private javax.swing.JRadioButton yes_Optioon1;
    // End of variables declaration//GEN-END:variables

    String path;
    String path1;

}
